# Generated by Django 4.1.4 on 2023-01-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_options_product_is_active_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='main.shop', verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
