# Generated by Django 4.1.4 on 2023-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_shop_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('basket', 'В корзине'), ('new', 'Новый заказ'), ('confirmed', 'Заказ подтвержден'), ('assembled', 'Заказ собран'), ('sent', 'Заказ отправлен'), ('delivered', 'Заказ доставлен'), ('canceled', 'Заказ отменен')], default='basket', max_length=15, verbose_name='Статус'),
        ),
    ]
